name = "embed"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-05-07"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
